// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
//using System.Threading.Tasks;
using UnityEngine;
using Verse.Sound;
using Verse;
using RimWorld;
namespace TrapPack
{
	public class ScorpionFlower : Plant
	{
		protected uint ticker_count;
		protected bool dyeing = false;
		public override void TickRare (){
			ticker_count++;
			if (surrounding_tiles_free(this.Position, this)){
				dyeing = false;
					base.TickRare();
				if (ticker_count % 100 == 1){
					Gas.try_place_Gas(this.Position, (GasDef)GasDef.Named("Scorpion_Flower_Spores"), 100, this.Faction);
				}
			}
		else{
				dyeing = true;
			if ((this.growthPercent -= .001f) < -.5){
					this.Destroy(DestroyMode.Kill);
			
			}
		}
		
		}
		
		public static bool surrounding_tiles_free(IntVec3 pos, Thing thing){
			foreach (IntVec3 test_pos in pos.AdjacentSquares8Way()){
				if (Find.ThingGrid.ThingAt(test_pos,thing.def) != null){
				return false;
				}
			}
			return true;
		
		}
		public override string GetInspectString ()
		{
			StringBuilder stringBuilder = new StringBuilder ();

				if (dyeing){
				stringBuilder.Append("Dyeing due to crowding. Grow your flowers separately.");
			}
			else{
				stringBuilder.Append (base.GetInspectString ());
			}
			return stringBuilder.ToString ();
		}
		
		
	}
}

